### PR TITLE
New rules and changes in MSTG-PLATFORM-6

### PR DESCRIPTION
**Pull request by federicodotta**
Hi!

Here the portion of [this pull request](https://github.com/mindedsecurity/semgrep-rules-android-security/pull/4) related only to rules 6.*.

The pull request contains the following updates (similar to the one we spoke [here](https://github.com/mindedsecurity/semgrep-rules-android-security/issues/2)):

* Rule MSTG-PLATFORM-6 (renamed to MSTG-PLATFORM-6.1) has been modified to handle the same scenarios as the previous one (a class that extends the WebView class). Due to the great variance of code (not simple to anticipate with SemGrep rules), it is possible that some scenarios may not be identified (es. symbolic_propagation is limited at the moment)
* Rule MSTG-PLATFORM-6.2 is a version of rule MSTG-PLATFORM-6.1 (old MSTG-PLATFORM-6) with a different approach. Rule MSTG-PLATFORM-6.1 searches for WebView definitions where methods that explicitly disable problematic features are not called (e.g., setAllowFileAccessFromFileURLs(false)). Many of those methods are disabled by default in newer versions of the Android API, which can lead to several false positives. However, in older versions, the situation was different, so I believe it is worth keeping this rule and creating another less specific one, even though it may cause some duplicates when both rules are executed. New rule looks at all calls to methods setAllowFileAccessFromFileURLs, setAllowUniversalAccessFromFileURLs, setAllowContentAccess and setAllowFileAccess when the argument is not the boolean "false"

Federico

### CODE REVIEW

**Comment by gand3lf** [comment]
Hi Federico!
The PR idea is good! But I have some doubts about it:
1. Could you merge the test files in order to not include new nomenclature? I think you can just append the content of the "-bis" rule in the other one.
2. What do you think about changing the rule as follows?
```yaml
    patterns:
      - pattern-either:
        - pattern: $B
        - pattern: $A.$B(true)
      - metavariable-pattern:
          metavariable: $B
          pattern-either:
            - pattern: setAllowContentAccess
            - pattern: setAllowFileAccess
            - pattern: setAllowFileAccessFromFileURLs
            - pattern: setAllowUniversalAccessFromFileURLs
```
3. Does it make sense for you to merge the rules 6.1 and the 6.2?
4. Maybe it could be better to shorten the warning message with something similar to this: 
``` 
The WebView allows to load external content. It is suggested to verify that the granted accesses are necessary and follow the best practices.
```

Hope this does not sound too pedantic! :smiley:

Thank you for the patience,
Riccardo

**Comment by federicodotta** [comment]
Hi Riccardo!

I answer point by point.

1. Done for both 6.1 and 6.2
2. Great idea to use metavariable-pattern to make the rule more readable! Yes, we can definitively change the rule as you suggested, but I think we have to change the code a little. Your rule match all the dangerous functions (setAllowContentAccess, ...) when are called with "true" as argument but the purpose of my original rule was to match when these methods are called with an argument different from "false", in order to allow to manual inspection when such method are called with a variable as argument (or the return value of a different function, ...). What do you thing about the following rule? If it is OK I will change rule 6.2 accordingly.

```yaml
    patterns:
      - pattern-either:
        - patterns:
          - pattern: $B(...)
          - pattern-not: $B(false)
        - patterns:
          - pattern: $A.$B(...)
          - pattern-not: $A.$B(false)
      - metavariable-pattern:
          metavariable: $B
          pattern-either:
            - pattern: setAllowContentAccess
            - pattern: setAllowFileAccess
            - pattern: setAllowFileAccessFromFileURLs
            - pattern: setAllowUniversalAccessFromFileURLs
```
3. I don't know. I think that rule 6.2 may work better on code of recent Android applications (where the default of those functions is "false") but rule 6.1 probably is better for old Android code (where many of dangerous functions had "true" as default value). For this reason maybe it may be worth it to keep them both, otherwise in order to avoid false negatives in all versions of Android probably we should add a generic rule that simply checks for the WebView object suggesting manual inspection.
4. Sure, done!

Thank you for the review and the suggestions! Please let me know how do you prefer to proceed.

Federico

**Comment by federicodotta** [comment]
Hi Riccardo,

OK, I will modified it this way. Maybe I add also the symbolic propagation option that may lower down the number of false positives.

Thank you!
Federico

**Comment by gand3lf** [comment]
Done, great work!
I hope you will continue to contribute to the project in the future.

Thank you Federico, you are a top player!
Riccardo

**Comment by federicodotta** [comment]
Thank you! Yes, I definitively will!

Thank you for your help and for having released such a great project! It's really helpfull for pentesters and developers!

Federico

**Pull request merged**
