### PR TITLE
New rules and changes in MSTG-PLATFORM-7

### PR DESCRIPTION
**Pull request by federicodotta**
Hi!

Here the portion of [this pull request](https://github.com/mindedsecurity/semgrep-rules-android-security/pull/4) related only to Rule 7.3.

The pull request contains the following updates (similar to the one we spoke [here](https://github.com/mindedsecurity/semgrep-rules-android-security/issues/2)):

* Rule MSTG-PLATFORM-7.3 has been added to handle scenarios where we inspect a class that extends the WebView class as well.

Federico

### CODE REVIEW

**Comment by gand3lf** [comment]
Hi Federico,
thanks for the PR! I agree with your rule and my question is only about the structure of the project. In this case, I would like to merge the PLATFORM-7.2 and the PLATFORM-7.3 in order to limit as much as possible the number of subversions of each rule. We are trying to split rules in more than one version only when:
- the rules require specific mode: join, taint
- the rule targets different file extensions

It is clear to me that you are proposing a new version because the warning messages are not perfectly compatible, but I propose to update the PLATFORM-7.2 in this way: https://semgrep.dev/playground/s/RDB2

About the metadata, it is clear that we should change the format of the "author" section in order to make simpler to add authors from different companies. I will change it asap, for now you can leave the author/company section proposed in the PR.
Does it sound good to you? If yes, please proceed by editing the PR.

Riccardo

**Comment by federicodotta** [comment]
Hi Riccardo!

I agree to keep the number of rules as small as possible. If you prefer, we can also merge 7.1 (but we loose many information in the message). Something like that:

https://semgrep.dev/playground/s/lgv5

Speaking on the metadata, thank you but I inserted my name only because I created a new file and I didn't want to create content on behalf of others. The original rule was yours, I only made small modification. I will leave you name as author.

Please let me know if you prefer a single rule (7) or two different rules (7.1 and 7.2).

Thank you,
Federico

**Comment by gand3lf** [comment]
Hi Federico,
good observation! Absolutely we should define some points to decide if a rule has to be split or not. In this case, I prefer to maintain the version 7.1 and 7.2 for these reasons:
- As you said, the more specific warning message.
- I would like to give the possibility to exclude the rule 7.1 from the scan because it can cause a large number of FP. In other words, I suppose that a single WebView can allow to expose a couple of classes, but the "@JavascriptInterface" annotation could be associated to hundreds of methods depending from the target application.

For the author issue, I will add you in any case when we change the template header of the author section! :blush:

Thank you,
Riccardo

**Comment by federicodotta** [comment]
Hi Riccardo!

I agree. Modified leaving 7.1 and 7.2 divided.

Thank you!
Federico

P.S. Great! You already merged! Thanks!

**Pull request merged**
